# Generated by Django 3.0.7 on 2021-02-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logindb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('upass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('land', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('regpass', models.CharField(max_length=50)),
            ],
        ),
    ]
