# Generated by Django 3.0.7 on 2021-02-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindb',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
